- src/ctap1.rs
- src/ctap2.rs
- src/lib.rs
This patch adds a configuration option to skip the additional user
presence check for the first Get Assertion or Authenticate request
within a certain duration after boot.  In this case, the device
insertion is interpreted as a user presence indicator.
> Skip user presence check directly after boot

- src/credential.rs
Instead of panicking, we now return a RequestTooLarge error if the
encrypted and serialized credential ID is longer than 255 bytes.
Fixes: https://github.com/solokeys/fido-authenticator/issues/15
> Return error if credential ID is too long

- Cargo.toml
- src/ctap2.rs
- src/ctap2/credential_management.rs
- src/state.rs
This patch bumps the Trussed dependency to include the update to littlefs2 0.4.0.
> Bump trussed

- src/ctap2.rs
- src/ctap2/credential_management.rs
https://github.com/Nitrokey/fido-authenticator/pull/12 (the credential limit checks) introduced a problem when overwriting resident keys:  We delete existing credentials with the same RP and user ID.  This can leave the RP directory empty, which is an invalid state and causes an error in the method that counts the resident keys to check the credential limit (`CredentialManagement::get_creds_metadata`).
This PR contains two fixes:
- `CredentialManagement::get_creds_metadata` now tolerates empty RP dirs.  They will still cause issues in other functions though.
- If we cannot store a resident key due to the credential limit or due to a filesystem error, we delete the RP directory if it is empty.
An alternative would be to remove the RP directory directly after deleting the existing …
> Fix overwriting resident keys

- src/ctap2.rs
This patch sets the makeCredUvNotRqd CTAP option to true to indicate that we support makeCredential operations without user verification. See also:
https://fidoalliance.org/specs/fido-v2.1-rd-20201208/fido-client-to-authenticator-protocol-v2.1-rd-20201208.html#getinfo-makecreduvnotrqd
Fixes: https://github.com/Nitrokey/fido-authenticator/issues/17
Upstream PR: https://github.com/solokeys/fido-authenticator/pull/27
> Set makeCredUvNotRqd in CTAP options

- src/ctap2.rs
The getAssertion command does not use the rk option so we return an InvalidOption error if it is set.
Fixes: https://github.com/Nitrokey/fido-authenticator/issues/23
Upstream PR: https://github.com/solokeys/fido-authenticator/pull/33
> Reject RK option in get_assertion

- src/state.rs
Previously, a PinAuthBlocked error was already returned after two wrong PIN entries. The reason for this as that decrement_retries also checks if the allowed retries are exceeded. This as unnecessary because pin_blocked is always checked before decrement_retries is called.
This patch removes the check in decrement_retries.
Fixes: https://github.com/Nitrokey/fido-authenticator/issues/27
Upstream PR: https://github.com/solokeys/fido-authenticator/pull/36
> Allow three instead of two PIN retries per boot

- src/ctap2.rs
Users with an empty ID should not be returned by getAssertion to avoid compatibility issues.
Fixes: https://github.com/Nitrokey/fido-authenticator/issues/24
Upstream PR: https://github.com/solokeys/fido-authenticator/pull/34
> Ignore user data with empty ID in get_assertion

- CHANGELOG.md
- src/ctap2.rs
This patch fixes two oversights in the recent PRs: missing changelog entries and a formatting error.
> Update changelog and fix formatting

- Cargo.toml
- src/credential.rs
- src/ctap2.rs
This PR uses the updated ctap-types crate that uses references rather than heapless buffers to reduce the total stack usage. See https://github.com/Nitrokey/ctap-types/pull/11
> Use references

- CHANGELOG.md
- Cargo.toml
- src/credential.rs
- src/ctap1.rs
- src/ctap2.rs
- src/ctap2/credential_management.rs
- src/state.rs
This patch implements the following changes to reduce the ID length for new credentials:
- Rename the old Credential type to FullCredential and introduce a StrippedCredential type and a Credential enum to differentiate between full and reduced credential data.
- Flatten the credential data to reduce encoding overhead.
- Remove the RP id from the credential data to reduce the total length.
- Add a marker field use_short_id to FullCredential so that we don’t change the credential ID for existing RKs.
To do:
- Can be done together with https://github.com/trussed-dev/fido-authenticator/issues/22.
- As we meet the size limit and the remaining fields only need one to four bytes, I think it’s not worth removing them with the risk that we might need them in the future.  We can still drop them if …
> Reduce ID length for new credentials

- CHANGELOG.md
- Cargo.toml
- src/dispatch/apdu.rs
This allows rejecting calls to `Select` over CCID
> Update apdu-dispatch 

- Cargo.toml
- src/ctap2.rs
- src/ctap2/large_blobs.rs
- src/lib.rs
- src/state.rs
This patch adds an implementation of the large-blob storage using the streaming API, making it possible to write data that is larger than 1024 bytes, the Trussed message size.
> Use streaming API for large blobs

- Cargo.toml
- examples/usbip.rs
This makes it faster to test with usbip than using the nitrokey-3-firmware usbip runner.
> Add `usbip` example

- src/ctap2.rs
- src/state.rs
If the user provides a wrong PIN and the persistent or per-boot PIN retry counter reaches its limit, we have to return the PinBlocked (persistent) or PinAuthBlocked (per boot) error code instead of PinInvalid.  The previous implementation checked the persistent retry counter twice instead of checking both counters.
This patch fixes this problem by using the combined State::pin_blocked method instead of manually checking the persistent and runtime state directly.
It also replaces a raw subtraction when computing the remaining retries with a saturating sub, just to be sure.
> Fix error type for third invalid PIN entry

- CHANGELOG.md
- src/lib.rs
This patch changes the error type that is returned if a user presence check is cancelled using the CTAPHID_CANCEL command from OPERATION_DENIED to KEEPALIVE_CANCEL.
> Fix error type for cancelled user presence

- CHANGELOG.md
- src/ctap2.rs
- src/ctap2/pin.rs
- src/state.rs
This patch extracts the implementation of PIN protocol one from the ctap2 and state modules into the ctap2.pin module.  This makes it easier to add support for PIN protocol two in the future.
Functionally, the extracted implementation should be mostly identical to the old implementation, expect for some smaller changes for improved compliance with the specification (error codes, explicit token resets).
> Extract PIN protocol implementation

- CHANGELOG.md
- Cargo.toml
- src/ctap1.rs
- src/ctap2.rs
- src/ctap2/pin.rs
- src/lib.rs
Based on:
- https://github.com/Nitrokey/fido-authenticator/pull/62
> Implement PIN protocol 2 and PIN token permissions

- src/ctap2.rs
- src/ctap2/pin.rs
- src/state.rs
This patch generates the key agreement key directly after the reset to improve the execution time of the next requests.  It also refactors the PIN token generation and storage so that the PIN token is only generated when needed, and only for the PIN protocol that is currently in use.
> Optimize key and PIN token generation

- Cargo.toml
- src/lib.rs
This patch adapts to the extraction of the extensions from trussed-staging, see:
https://github.com/trussed-dev/trussed-staging/pull/19
> Use trussed-chunked instead of trussed-staging

- .github/workflows/ci.yml
- Cargo.toml
- examples/usbip.rs
- tests/basic.rs
- tests/virt/dispatch.rs
- tests/virt/mod.rs
- tests/virt/pipe.rs
- tests/webauthn/mod.rs
This patch adds basic integration tests that use the ctaphid library to send CTAPHID commands to the authenticator over ctaphid-dispatch. Unfortunately, usbd-ctaphid does not provide a public interface to its packet handling code, so we have to copy that code for the time being.
> Setup basic integration tests

- Cargo.toml
- tests/basic.rs
- tests/virt/mod.rs
- tests/virt/pipe.rs
- tests/webauthn/mod.rs
This PR improves the infrastructure for the test suite and also adds some tests for basic credential management that reproduce https://github.com/Nitrokey/fido-authenticator/issues/80 (if enabled).
To do:
> Extend test suite with basic credential management

- src/ctap2.rs
- src/ctap2/pin.rs
- tests/basic.rs
As described in #80, we currently require PIN tokens without an RP ID restriction for all credential management operations.  For most operations, this is correct.
For EnumerateCredentialsBegin, we should also accept a token that matches the requested RP ID hash.  For DeleteCredential and UpdateUserInformation, we should also accept a token that matches the requested credential ID.  As it is not trivial to compare the RP ID hash or the credential ID against the RP ID set for the PIN token, I did not handle these cases in the initial implementation.
This led to an incompatibility with libfido2 because it tries to use a restricted PIN token to enumerate credentials.  With this patch, we additionally compute the RP ID hash when restricting a PIN token to an RP ID and use that to validate the …
> Accept scoped PIN tokens for EnumerateCredentialsBegin

- Cargo.toml
- src/credential.rs
- src/ctap1.rs
- src/ctap2.rs
- src/ctap2/credential_management.rs
- src/ctap2/pin.rs
- src/dispatch.rs
- src/lib.rs
- src/state.rs
This patch replaces our duplicated COSE implementation with the `cosey` crate and updates the `ctap-types` dependency.
> Use cosey and update ctap_types

- Cargo.toml
- fuzz/Cargo.toml
- src/credential.rs
- src/ctap1.rs
- src/ctap2.rs
- src/ctap2/credential_management.rs
- src/state.rs
- tests/basic.rs
- tests/webauthn/mod.rs
- Implement the `thirdPartyPayment` extension
- Add support for attestation format preferences
- Add support for attestation in `get_assertion`
- Add extensive tests for the new features
> Implement CTAP 2.2

- CHANGELOG.md
- Cargo.toml
- fuzz/Cargo.toml
- src/state.rs
Reduce the storage space used by the hash of the PIN by using serde-byte-array. Fix #49 
Needs https://github.com/nickray/cbor-smol/pull/7 to properly deserialize credentials that were serialize prior to this PR such as the one in the test.
> Pin hash space opt

- Cargo.toml
- fuzz/Cargo.toml
- src/ctap2.rs
- src/ctap2/credential_management.rs
- src/ctap2/large_blobs.rs
- src/lib.rs
The estimation is pretty rough and in most cases pessimistic. It reserves multiple blocks of margin to prevent filling up the device.
With the default configuration of the usbip runner, it estimates the value to be around 40, and I could generate more than 60.
For now, this PR removes the hard-coded limitation when generating credentials.
This makes credential generation faster, but at the same time this could prove to be an issue when listing credential (even the USBIP version is pretty slow to list all credentials).
> Add dynamic estimation of remaining credential space

- CHANGELOG.md
- Cargo.toml
- src/credential.rs
- src/ctap2.rs
- src/ctap2/credential_management.rs
This saves space when serializing credentials.
We cannot use [`#[serde(remote)]`](https://serde.rs/remote-derive.html) because that would require supporting `#[serde(with)]` in `serde_indexed`, already used for `CredentialData`
This replaces #58 it should be 1 bytes larger per serialized fields, but is better than serde-indexed as it has les risks to break accidentally when adding/removing a field.
> Serialize credential with fields names using only 1 bytes

- tests/authenticator/mod.rs
- tests/basic.rs
- tests/cred_mgmt.rs
- tests/ctap1.rs
- tests/virt/mod.rs
- tests/webauthn/mod.rs
This patch introduces the authenticator module that provides a simple high-level interface for testing FIDO2 functionality.  It uses the module to implement tests for credential management, namely for listing credentials and for the behavior if the credential limit is reached or the filesystem is full.
> tests: Add credential management tests

- src/ctap2/credential_management.rs
- tests/cred_mgmt.rs
We have two limits for the credential count:  a fixed limit determined by the configuration and an estimated limit based on the remaining filesystem size.  When creating a new credential, we check both.  But previously we only returned the estimated limit from get_creds_metadata. This patch adds the fixed limit to get_creds_metadata.
> Check credential limit in get_creds_metadata

- Cargo.toml
We only have an explicit cbor-smol dependency to make sure that at least v0.4.1 is selected so that the persistent state is deserialized correctly.  Trussed has a more specific version constraint so we can only enforce the mininum version here.
> Relax cbor-smol dependency

- src/ctap2/pin.rs
- src/lib.rs
- src/state.rs
The cbor_serialize_message helper mixed re-exports of cbor-smol from trussed and ctap-types.  This can be problematic if both select different versions.  It could be fixed by keeping both in sync, but to avoid this problem entirely, we can also just use cbor_serialize_bytes from Trussed directly.
> Remove cbor_serialize_message helper

- src/ctap2/credential_management.rs
- src/state.rs
Some small fixes for https://github.com/Nitrokey/fido-authenticator/pull/55.  They should eventually be squashed into the parent commit but for transparency during the review, I wanted to keep and merge them separately.
- We set `total_credentials` to `Some(num_rks)` just before accessing it, so we don’t need to go through the option.
- `prev_filename` is always set to `Some` so we can remove the `Option`.
- `rp_dir` is now always `RK_DIR` so we don’t need to cache it.
> space-opt-migration: Small fixes

- src/credential.rs
- src/ctap2/credential_management.rs
To simplify the Rp and User types introduced in the last commit and to reduce code duplication, this patch removes the
`LocalPublicKeyCredential*Entity` types.  Instead the Rp and User types always store a `PublicKeyCredential*Entity` together with the serialization format.
----
This reduces the overall diff from main and also significantly decreases binary size compared to the current credential-id branch (not entirely sure why).
> Remove LocalPublicKeyCredential*Entity structs

- Cargo.toml
- src/credential.rs
- src/ctap2.rs
- src/ctap2/credential_management.rs
In https://github.com/Nitrokey/fido-authenticator/pull/59, we changed the format for serialized credentials to use shorter field names for the RP and user entities.  This has an unintended side effect:  For non-discoverable credentials that were generated with older crate versions, the stripped data embedded into the credential ID includes the RP and user.  If we change their serialization format, we also change these credential IDs.
We already supported deserializing both formats using a serde alias. This patch introduces helper enums that deserialize both formats using a custom Deserialize implementation and keep track of the used format. This format is then also used for serialization (using serde’s untagged mechanism that is not available for deserialization in no-std contexts). …
> Keep old credential ID for existing credentials

- tests/authenticator/mod.rs
- tests/basic.rs
- tests/cred_mgmt.rs
- tests/webauthn/mod.rs
This patch adds tests for deleting discoverable credentials and for updating the user information for existing credentials.
> Extend credential management tests

- .cargo/config
- Cargo.toml
This patch adds the missing log-trace feature and removes the deprecated and unnecessary `.cargo/config` file.
> Fix compiler warnings

- Cargo.toml
- tests/basic.rs
- tests/cred_mgmt.rs
- tests/fs/mod.rs
- tests/virt/mod.rs
- tests/webauthn/mod.rs
This PR extends the integration test suite to:
- Cover more cases in makeCredential and getAssertion tests (rks, option combinations, allow lists, ...).
- Test bad getPinToken and setPin calls.
- Add tests for getPinRetries, changePin and getNextAssertion.
- Inspect the IFS after running the tests to check the directory structure and ensure that deletion works.
The new tests already caught two bugs and points us to some error codes that need to be reviewed.
- https://github.com/Nitrokey/fido-authenticator/issues/119
- https://github.com/Nitrokey/fido-authenticator/issues/120
> Extend integration tests

- CHANGELOG.md
- Cargo.toml
- src/ctap2.rs
- src/ctap2/credential_management.rs
- src/lib.rs
- src/state.rs
- src/state/migrate.rs
- tests/cred_mgmt.rs
- tests/fs/mod.rs
For now the migration step renames the files, testing need to be done to make sure that this will not fail when only one block remains free.
> Reduce space taken by credentials, using a migration step

- src/credential.rs
- src/ctap2.rs
- src/ctap2/credential_management.rs
- src/lib.rs
This PR removes dead code referencing the non-standard TOTP signing algorithm and reduces code duplication for key generation and signing operations.
> Clean up signing algorithms

- src/ctap2.rs
- tests/basic.rs
- tests/webauthn/mod.rs
This PR extends the test suite with tests for the hmac-secret extension and fixes its implementation to reject requests with up set to false.
Fixes: https://github.com/Nitrokey/fido-authenticator/issues/19
> hmac-secret: Forbid up=false
